### PR TITLE
Bump to 0.9.1

### PR DESCRIPTION
**Pull request by bollwyvl**
Howdy!

This PR:
- updates to most recent PyPI upstream, `0.9.1`
- add `noarch: python`
- add `description` from homepage
- add myself as a `maintainer`
  > @rhiever would you like to be added as well?
- change `license` to canonical (SPDX) string
- add new `run` dependency `stopit`
- update `run` dependency minimum versions
- update `imports` to new API
- re-rendered with conda-smithy 2.4.5
  - will only run (wicked fast) on CircleCI

I didn't add test running under `nose`, as they are not in the source distribution, but did open a [PR](https://github.com/rhiever/tpot/pull/649) to make this possible in the future... this will be good to further test its [new optional dependencies](https://github.com/conda-forge/staged-recipes/pull/4708) as well as `xgboost` and others!

### CODE REVIEW

**Comment by bollwyvl** [comment]
Gotta love that fast `noarch` CI!

**Comment by proinsias** [comment]
Thanks!

**Comment by bollwyvl** [comment]
Thanks @prosinias!

But... Uhoh. The circle build failed due to a bad GitHub ssh key.
Apparently the feedstock has to be "readded"... Wsaccel-feedstock just had
to do this, for example. I'm afk at present, but the gitter folks might be
able to help...

**Comment by bollwyvl** [comment]
Gah, @proinsias, i mistyped your name, and it was eaten by my phone anyway.

I've gone ahead and re-submitted to get a new GH SSH key on https://github.com/conda-forge/staged-recipes/pull/4747 !

Thanks again!

**Pull request merged**
