### PR TITLE
Add tpot full

### LINKED ISSUE #19: Feature Request: option to install other dependencies
Following https://github.com/EpistasisLab/tpot/issues/1005#issuecomment-575860780 it was suggested that an option for installing tpot with other dependencies could be a conda-forge install called tpot-full. This would get additional optional packages and would be smarter with version pinning/testing than a blanket install command (https://github.com/EpistasisLab/tpot/pull/1006/files)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- fixes #19 

This adds `tpot-full` with the whole raft of extra dependencies, previously only used in test. Everything can _still_ be `noarch: python` (:tada:) which is awesome, but I haven't tested this on OSX/Windows in a while, so we're really hoping for the best here... but I can't in good conscience un-noarch this just to get tests (conda-forge is not continuous integration). But since this doesn't really change anything, I think it's fine, and we'll just want to run a test offline. 

Speaking of tests:  the test running has moved to `tpot-full` (since the tests fail without all the extra deps). This in fact moves the _files_ from the tests into `tpot-full`, which reduces the size of the `tpot` (:tada:). `tpot` is then only tested with the main import, and CLI entry points, and `pip check`, which would scare me, except that we're doing the full test immediately thereafter.

On the whole I think this is a pretty good solution, as you'll be able to say!

```bash
conda install -c conda-forge tpot-full
```

And get a whole _heap_ of value.

It's fairly easy to robustly make more metapackages. If desirable, we could add `tpot-dask`, `tpot-xgboost`, `tpot-skrebate`, `tpot-mdr`, and make `tpot-full` depend on all of _those_... but the only reason i could imagine wanting not-`full` is on a very constrained platform that didn't have some of the deps of `full` for some reason. Note that i can at least _solve_ this environment on OSX, while on windows... _something_ fails. I can run this down further, but would again, see the points above. 

<details>
<summary>
<code>CONDA_SUBDIR=osx-64 conda create -c conda-forge --use-local -n foo --dry-run tpot-full
</code>
</summary>
<code><pre>

  _py-xgboost-mutex  conda-forge/osx-64::_py-xgboost-mutex-2.0-cpu_0
  bokeh              conda-forge/osx-64::bokeh-1.4.0-py38_0
  ca-certificates    conda-forge/osx-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/osx-64::certifi-2019.11.28-py38_0
  cffi               conda-forge/osx-64::cffi-1.13.2-py38h33e799b_0
  chardet            conda-forge/osx-64::chardet-3.0.4-py38_1003
  click              conda-forge/noarch::click-7.0-py_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.2.2-py_1
  cryptography       conda-forge/osx-64::cryptography-2.8-py38hafa8578_1
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  cytoolz            conda-forge/osx-64::cytoolz-0.10.1-py38h0b31af3_0
  dask               conda-forge/noarch::dask-2.9.2-py_0
  dask-core          conda-forge/noarch::dask-core-2.9.2-py_0
  dask-glm           conda-forge/noarch::dask-glm-0.2.0-py_1
  dask-ml            conda-forge/noarch::dask-ml-1.2.0-py_0
  deap               conda-forge/osx-64::deap-1.3.0-py38h4f17bb1_0
  distributed        conda-forge/noarch::distributed-2.9.3-py_0
  freetype           conda-forge/osx-64::freetype-2.10.0-h24853df_1
  fsspec             conda-forge/noarch::fsspec-0.6.2-py_0
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  idna               conda-forge/osx-64::idna-2.8-py38_1000
  jinja2             conda-forge/noarch::jinja2-2.10.3-py_0
  joblib             conda-forge/noarch::joblib-0.14.1-py_0
  jpeg               conda-forge/osx-64::jpeg-9c-h1de35cc_1001
  kiwisolver         conda-forge/osx-64::kiwisolver-1.1.0-py38ha1b3eb9_0
  libblas            conda-forge/osx-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/osx-64::libcblas-3.8.0-14_openblas
  libcxx             conda-forge/osx-64::libcxx-9.0.1-1
  libffi             conda-forge/osx-64::libffi-3.2.1-h6de7cb9_1006
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-2
  liblapack          conda-forge/osx-64::liblapack-3.8.0-14_openblas
  libllvm8           conda-forge/osx-64::libllvm8-8.0.1-h770b8ee_0
  libopenblas        conda-forge/osx-64::libopenblas-0.3.7-h3d69b6c_7
  libpng             conda-forge/osx-64::libpng-1.6.37-h2573ce8_0
  libtiff            conda-forge/osx-64::libtiff-4.1.0-ha78913b_3
  libxgboost         conda-forge/osx-64::libxgboost-0.90-h4a8c4bd_4
  llvm-openmp        conda-forge/osx-64::llvm-openmp-9.0.1-h28b9765_1
  llvmlite           conda-forge/osx-64::llvmlite-0.31.0-py38h05045ef_0
  locket             conda-forge/noarch::locket-0.2.0-py_2
  lz4-c              conda-forge/osx-64::lz4-c-1.8.3-h6de7cb9_1001
  markupsafe         conda-forge/osx-64::markupsafe-1.1.1-py38h0b31af3_0
  matplotlib         conda-forge/osx-64::matplotlib-3.1.2-py38_1
  matplotlib-base    conda-forge/osx-64::matplotlib-base-3.1.2-py38h11da6c2_1
  msgpack-python     conda-forge/osx-64::msgpack-python-0.6.2-py38ha1b3eb9_0
  multipledispatch   conda-forge/noarch::multipledispatch-0.6.0-py_0
  ncurses            conda-forge/osx-64::ncurses-6.1-h0a44026_1002
  numba              conda-forge/osx-64::numba-0.47.0-py38h4f17bb1_0
  numpy              conda-forge/osx-64::numpy-1.17.3-py38hde6bac1_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openssl            conda-forge/osx-64::openssl-1.1.1d-h0b31af3_0
  packaging          conda-forge/noarch::packaging-20.0-py_0
  pandas             conda-forge/osx-64::pandas-0.25.3-py38h4f17bb1_0
  partd              conda-forge/noarch::partd-1.1.0-py_0
  pillow             conda-forge/osx-64::pillow-7.0.0-py38h918e99a_0
  pip                conda-forge/osx-64::pip-19.3.1-py38_0
  psutil             conda-forge/osx-64::psutil-5.6.7-py38h0b31af3_0
  py-xgboost         conda-forge/osx-64::py-xgboost-0.90-py38_4
  pycparser          conda-forge/osx-64::pycparser-2.19-py38_1
  pyopenssl          conda-forge/osx-64::pyopenssl-19.1.0-py38_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py38_0
  python             conda-forge/osx-64::python-3.8.1-h5c2c468_1
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  pyyaml             conda-forge/osx-64::pyyaml-5.3-py38h0b31af3_0
  readline           conda-forge/osx-64::readline-8.0-hcfe32e1_0
  requests           conda-forge/osx-64::requests-2.22.0-py38_1
  scikit-learn       conda-forge/osx-64::scikit-learn-0.22.1-py38h3dc85bc_1
  scikit-mdr         conda-forge/noarch::scikit-mdr-0.4.4-py_0
  scipy              conda-forge/osx-64::scipy-1.4.1-py38h82752d6_0
  setuptools         conda-forge/osx-64::setuptools-45.0.0-py38_1
  six                conda-forge/osx-64::six-1.14.0-py38_0
  skrebate           conda-forge/noarch::skrebate-0.6-py_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.1.0-py_0
  sqlite             conda-forge/osx-64::sqlite-3.30.1-h93121df_0
  stopit             conda-forge/noarch::stopit-1.1.2-py_0
  tblib              conda-forge/noarch::tblib-1.6.0-py_0
  tk                 conda-forge/osx-64::tk-8.6.10-hbbe82c9_0
  toolz              conda-forge/noarch::toolz-0.10.0-py_0
  tornado            conda-forge/osx-64::tornado-6.0.3-py38h0b31af3_0
  tpot               home/weg/mc3/conda-bld/noarch::tpot-0.11.1-py_1
  tpot-full          home/weg/mc3/conda-bld/noarch::tpot-full-0.11.1-py_1
  tqdm               conda-forge/noarch::tqdm-4.41.1-py_0
  update_checker     conda-forge/noarch::update_checker-0.16-py_0
  urllib3            conda-forge/osx-64::urllib3-1.25.7-py38_0
  wheel              conda-forge/osx-64::wheel-0.33.6-py38_0
  xz                 conda-forge/osx-64::xz-5.2.4-h1de35cc_1001
  yaml               conda-forge/osx-64::yaml-0.2.2-h0b31af3_1
  zict               conda-forge/noarch::zict-1.0.0-py_0
  zlib               conda-forge/osx-64::zlib-1.2.11-h0b31af3_1006
  zstd               conda-forge/osx-64::zstd-1.4.4-he7fca8b_1
</pre></code>
</details>

 
@proinsias @raybellwaves Thoughts?

### CODE REVIEW

**Comment by bollwyvl** [comment]
Ah, the bad-un is `py-xgboost`, which is not available for [windows](https://github.com/conda-forge/xgboost-feedstock/issues/3).

So perhaps there is:
- `tpot-full` for unix folks
- `tpot-full-noxgboost` for the windows crowd? 

Or we throw some effort at `xgboost` (somewhat terrifying, frankly).

**Comment by raybellwaves** [comment]
Thanks @bollwyvl 

> tpot-full-noxgboost for the windows crowd?

Seems like a reasonable option. Perhaps after running this they can do `conda install -c conda-forge py-xgboost` (https://anaconda.org/conda-forge/py-xgboost). Not really sure how to test here though.

I'm still curious at the difference between `py-xgboost` and `xgboost`. The `py-xgboost` install on my linux machine in a fresh env downloads:

<details>
(test_env) ray@ray-MS-7B43:~$ conda install -c conda-forge py-xgboost
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ray/local/bin/anaconda3/envs/test_env

  added / updated specs:
    - py-xgboost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.11.28         |           py37_0         148 KB  conda-forge
    numpy-1.17.5               |   py37h95a1406_0         5.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.3 MB

The following NEW packages will be INSTALLED:

  _py-xgboost-mutex  conda-forge/linux-64::_py-xgboost-mutex-2.0-cpu_0
  joblib             conda-forge/noarch::joblib-0.14.1-py_0
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_4
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libxgboost         conda-forge/linux-64::libxgboost-0.90-he1b5a44_4
  numpy              conda-forge/linux-64::numpy-1.17.5-py37h95a1406_0
  py-xgboost         conda-forge/linux-64::py-xgboost-0.90-py37_4
  scikit-learn       conda-forge/linux-64::scikit-learn-0.22.1-py37hcdab131_1
  scipy              conda-forge/linux-64::scipy-1.4.1-py37h921218d_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.11.27~ --> conda-forge::ca-certificates-2019.11.28-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.1.1d-h7b6447c_3 --> conda-forge::openssl-1.1.1d-h516909a_0

</details>

The `xgboost` install downloads the same packages: `py-xgboost` is included and `xgboost`.

<details>
(test_env) ray@ray-MS-7B43:~$ conda install -c conda-forge xgboost
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ray/local/bin/anaconda3/envs/test_env

  added / updated specs:
    - xgboost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.11.28         |           py37_0         148 KB  conda-forge
    numpy-1.17.5               |   py37h95a1406_0         5.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.3 MB

The following NEW packages will be INSTALLED:

  _py-xgboost-mutex  conda-forge/linux-64::_py-xgboost-mutex-2.0-cpu_0
  joblib             conda-forge/noarch::joblib-0.14.1-py_0
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_4
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libxgboost         conda-forge/linux-64::libxgboost-0.90-he1b5a44_4
  numpy              conda-forge/linux-64::numpy-1.17.5-py37h95a1406_0
  py-xgboost         conda-forge/linux-64::py-xgboost-0.90-py37_4
  scikit-learn       conda-forge/linux-64::scikit-learn-0.22.1-py37hcdab131_1
  scipy              conda-forge/linux-64::scipy-1.4.1-py37h921218d_0
  xgboost            conda-forge/linux-64::xgboost-0.90-py37he1b5a44_4

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.11.27~ --> conda-forge::ca-certificates-2019.11.28-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.1.1d-h7b6447c_3 --> conda-forge::openssl-1.1.1d-h516909a_0

</details>

I also wanted to see what there difference was on my windows laptop (yep no `xgboost`) but `py-xgboost` is ok:
<details>
(test_env) C:\>conda install -c conda-forge py-xgboost
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env

  added / updated specs:
    - py-xgboost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _py-xgboost-mutex-2.0      |            cpu_0          12 KB
    certifi-2019.11.28         |           py37_0         148 KB  conda-forge
    joblib-0.14.1              |             py_0         198 KB  conda-forge
    libxgboost-0.90            |                1         1.8 MB
    numpy-1.17.5               |   py37hc71023c_0         4.6 MB  conda-forge
    py-xgboost-0.90            |           py37_1          78 KB
    scikit-learn-0.22.1        |   py37h7208079_1         6.1 MB  conda-forge
    six-1.14.0                 |           py37_0          23 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        12.9 MB

The following NEW packages will be INSTALLED:

  _py-xgboost-mutex  pkgs/main/win-64::_py-xgboost-mutex-2.0-cpu_0
  blas               pkgs/main/win-64::blas-1.0-mkl
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       pkgs/main/win-64::intel-openmp-2019.4-245
  joblib             conda-forge/noarch::joblib-0.14.1-py_0
  libblas            conda-forge/win-64::libblas-3.8.0-14_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-14_mkl
  liblapack          conda-forge/win-64::liblapack-3.8.0-14_mkl
  libxgboost         pkgs/main/win-64::libxgboost-0.90-1
  m2w64-gcc-libgfor~ pkgs/msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     pkgs/msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          pkgs/msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ pkgs/msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  mkl                pkgs/main/win-64::mkl-2019.4-245
  mkl-service        conda-forge/win-64::mkl-service-2.3.0-py37hfa6e2cd_0
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  numpy              conda-forge/win-64::numpy-1.17.5-py37hc71023c_0
  py-xgboost         pkgs/main/win-64::py-xgboost-0.90-py37_1
  scikit-learn       conda-forge/win-64::scikit-learn-0.22.1-py37h7208079_1
  scipy              pkgs/main/win-64::scipy-1.3.2-py37h29ff71c_0
  six                conda-forge/win-64::six-1.14.0-py37_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.11.27~ --> conda-forge::ca-certificates-2019.11.28-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.1.1d-he774522_3 --> conda-forge::openssl-1.1.1d-hfa6e2cd_0
</details>

<details>
(test_env) C:\>conda install -c conda-forge xgboost
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - xgboost

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
</details>

Lastly, I wanted to test the current `tpot` installation command followed by the `py-xgboost` install command on my windows laptop:

<details>
(test_env) C:\>conda install -c conda-forge tpot
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env

  added / updated specs:
    - tpot


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.11.28         |           py37_0         148 KB  conda-forge
    chardet-3.0.4              |        py37_1003         184 KB  conda-forge
    deap-1.3.0                 |   py37he350917_0         152 KB  conda-forge
    joblib-0.14.1              |             py_0         198 KB  conda-forge
    numpy-1.17.5               |   py37hc71023c_0         4.6 MB  conda-forge
    pyopenssl-19.1.0           |           py37_0          83 KB  conda-forge
    pysocks-1.7.1              |           py37_0          27 KB  conda-forge
    python-dateutil-2.8.1      |             py_0         220 KB  conda-forge
    pytz-2019.3                |             py_0         237 KB  conda-forge
    requests-2.22.0            |           py37_1          84 KB  conda-forge
    scikit-learn-0.22.1        |   py37h7208079_1         6.1 MB  conda-forge
    six-1.14.0                 |           py37_0          23 KB  conda-forge
    stopit-1.1.2               |             py_0          16 KB  conda-forge
    tpot-0.11.1                |             py_0          75 KB  conda-forge
    tqdm-4.41.1                |             py_0          45 KB  conda-forge
    update_checker-0.16        |             py_0           9 KB  conda-forge
    urllib3-1.25.7             |           py37_0         159 KB  conda-forge
    win_inet_pton-1.1.0        |           py37_0           7 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        12.3 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  cffi               conda-forge/win-64::cffi-1.13.2-py37hb32ad35_0
  chardet            conda-forge/win-64::chardet-3.0.4-py37_1003
  cryptography       conda-forge/win-64::cryptography-2.8-py37hb32ad35_1
  deap               conda-forge/win-64::deap-1.3.0-py37he350917_0
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  idna               conda-forge/win-64::idna-2.8-py37_1000
  intel-openmp       pkgs/main/win-64::intel-openmp-2019.4-245
  joblib             conda-forge/noarch::joblib-0.14.1-py_0
  libblas            conda-forge/win-64::libblas-3.8.0-14_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-14_mkl
  liblapack          conda-forge/win-64::liblapack-3.8.0-14_mkl
  mkl                pkgs/main/win-64::mkl-2019.4-245
  mkl-service        conda-forge/win-64::mkl-service-2.3.0-py37hfa6e2cd_0
  numpy              conda-forge/win-64::numpy-1.17.5-py37hc71023c_0
  pandas             conda-forge/win-64::pandas-0.25.3-py37he350917_0
  pycparser          conda-forge/win-64::pycparser-2.19-py37_1
  pyopenssl          conda-forge/win-64::pyopenssl-19.1.0-py37_0
  pysocks            conda-forge/win-64::pysocks-1.7.1-py37_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  requests           conda-forge/win-64::requests-2.22.0-py37_1
  scikit-learn       conda-forge/win-64::scikit-learn-0.22.1-py37h7208079_1
  scipy              pkgs/main/win-64::scipy-1.3.2-py37h29ff71c_0
  six                conda-forge/win-64::six-1.14.0-py37_0
  stopit             conda-forge/noarch::stopit-1.1.2-py_0
  tpot               conda-forge/noarch::tpot-0.11.1-py_0
  tqdm               conda-forge/noarch::tqdm-4.41.1-py_0
  update_checker     conda-forge/noarch::update_checker-0.16-py_0
  urllib3            conda-forge/win-64::urllib3-1.25.7-py37_0
  win_inet_pton      conda-forge/win-64::win_inet_pton-1.1.0-py37_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.11.27~ --> conda-forge::ca-certificates-2019.11.28-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.1.1d-he774522_3 --> conda-forge::openssl-1.1.1d-hfa6e2cd_0




(test_env) C:\>conda install -c conda-forge py-xgboost
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env

  added / updated specs:
    - py-xgboost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _py-xgboost-mutex-2.0      |            cpu_0          12 KB
    libxgboost-0.90            |                1         1.8 MB
    py-xgboost-0.90            |           py37_1          78 KB
    ------------------------------------------------------------
                                           Total:         1.9 MB

The following NEW packages will be INSTALLED:

  _py-xgboost-mutex  pkgs/main/win-64::_py-xgboost-mutex-2.0-cpu_0
  libxgboost         pkgs/main/win-64::libxgboost-0.90-1
  m2w64-gcc-libgfor~ pkgs/msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     pkgs/msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          pkgs/msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ pkgs/msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  py-xgboost         pkgs/main/win-64::py-xgboost-0.90-py37_1


Proceed ([y]/n)?


Downloading and Extracting Packages
libxgboost-0.90      | 1.8 MB    | ####################################################################################################################################################################### | 100%
py-xgboost-0.90      | 78 KB     | ####################################################################################################################################################################### | 100%
_py-xgboost-mutex-2. | 12 KB     | ####################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(test_env) C:\>python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tpot import TPOTClassifier
>>> from sklearn.datasets import load_digits
>>> from sklearn.model_selection import train_test_split
>>>
>>> digits = load_digits()
>>> X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
...                                                     train_size=0.75, test_size=0.25)
>>>
>>> tpot = TPOTClassifier(verbosity=2, max_time_mins=2, population_size=40)
>>> tpot.fit(X_train, y_train)
Warning: xgboost.XGBClassifier is not available and will not be used by TPOT.

2.07 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: GradientBoostingClassifier(input_matrix, learning_rate=0.1, max_depth=10, max_features=0.2, min_samples_leaf=3, min_samples_split=7, n_estimators=100, subsample=0.8500000000000001)
TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=100,
               max_eval_time_mins=5, max_time_mins=2, memory=None,
               mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=40,
               random_state=None, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)

(test_env) C:\>conda install -c conda-forge py-xgboost

(test_env) C:\>conda install -c conda-forge py-xgboost
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\131416\AppData\Local\Continuum\anaconda3\envs\test_env

  added / updated specs:
    - py-xgboost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    py-xgboost-0.90            |           py36_1          78 KB
    ------------------------------------------------------------
                                           Total:          78 KB

The following NEW packages will be INSTALLED:

  _py-xgboost-mutex  pkgs/main/win-64::_py-xgboost-mutex-2.0-cpu_0
  libxgboost         pkgs/main/win-64::libxgboost-0.90-1
  m2w64-gcc-libgfor~ pkgs/msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     pkgs/msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          pkgs/msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ pkgs/msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  py-xgboost         pkgs/main/win-64::py-xgboost-0.90-py36_1

(test_env) C:\>python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tpot import TPOTClassifier
>>> from sklearn.datasets import load_digits
>>> from sklearn.model_selection import train_test_split
>>>
>>> digits = load_digits()
>>> X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
...                                                     train_size=0.75, test_size=0.25)
>>>
>>> tpot = TPOTClassifier(verbosity=2, max_time_mins=2, population_size=40)
>>> tpot.fit(X_train, y_train)

2.40 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: GradientBoostingClassifier(MaxAbsScaler(input_matrix), learning_rate=0.1, max_depth=6, max_features=0.3, min_samples_leaf=3, min_samples_split=11, n_estimators=100, subsample=0.4)
TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=100,
               max_eval_time_mins=5, max_time_mins=2, memory=None,
               mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=40,
               random_state=None, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)

</details>

**Comment by bollwyvl** [comment]
(py-)xgboost is not available from conda-forge on windows. The naming
difference may be historical...

**Comment by bollwyvl** [comment]
On windows, a user _can_ get `py-xgboost == 0.90` from `anaconda` (probably because someone paid Anaconda to build it for windows), and most folk _will_ be pulling things from both. Usually works out fine! Not sure in this case, however, as I'm not directly involved in maintaining `xgboost`.

However, when we build/test packages for `conda-forge`, we _don't_ assume that `anaconda` will be there, because, practically, `conda-forge` is the _upstream_ of `anaconda`.

**Comment by bollwyvl** [comment]
More trouble:
- https://github.com/EpistasisLab/tpot/issues/1069#issuecomment-636259842
- https://github.com/EpistasisLab/tpot/issues/1075

**Comment by jakirkham** [comment]
In case it helps, `py-xgboost` got updated recently ( https://github.com/conda-forge/xgboost-feedstock/pull/50 ).

**Comment by bollwyvl** [comment]
> py-xgboost got updated recently

awesome! but still no windows, which is kind of the kicker to making this `full` work predictably for users (part of why i haven't picked it back up)...

**Comment by jakirkham** [comment]
Yeah Windows is hard unfortunately ( https://github.com/conda-forge/xgboost-feedstock/issues/3 ) 😞 Help with that would certainly be appreciated 🙂

**Comment by bollwyvl** [comment]
Oh, I know, and I appreciate all the efforts... Problem is if I got a
windows box, i'd just play games on it...

**Comment by bollwyvl** [comment]
time to warm this back up! through some act of heroism we got https://github.com/conda-forge/xgboost-feedstock/pull/60 ! might be this weekend before i get to it, however...

**Comment by jakirkham** [comment]
Definitely! Will be interesting to see the things that work unlocks 😄

**Comment by bollwyvl** [comment]
Merging now, will try in a more aggressive test environment tomorrow...

**Pull request merged**
