### PR TITLE
new tpot owner: epistasislab

### PR DESCRIPTION
**Pull request by bosr**
Hi `tpot` previous owner (rhiever) has given ownership to EpistasisLab.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
I'll take a look more into the test fails, obviously those didn't happen before when we pushed out the previous builds of this version. If you have any insights as to what might have changed...

**Comment by bosr** [comment]
Thanks, unfortunately, I don't have a clue :/

**Comment by bollwyvl** [comment]
Well, we're skipping a few tests, but everything else is looking okay. Off we go, thanks @bosr!

**Comment by bollwyvl** [comment]
@bosr please let me know if you are interested in helping maintain the recipe! We always need more sharp-eyed users to keep us honest!

**Comment by bosr** [comment]
Thanks Nicolas! I would like to but I’m not sure I currently have enough bandwidth. 

Cheers!

**Pull request merged**
